CREATE DATABASE IF NOT EXISTS carproject;
USE carproject;

CREATE TABLE IF NOT EXISTS users (
    FNAME VARCHAR(255) NOT NULL,
    LNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL PRIMARY KEY,
    LIC_NUM VARCHAR(255) NOT NULL,
    PHONE_NUMBER BIGINT NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    GENDER VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS cars (
    CAR_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAR_NAME VARCHAR(255) NOT NULL,
    FUEL_TYPE VARCHAR(100) NOT NULL,
    CAPACITY INT NOT NULL,
    PRICE INT NOT NULL,
    CAR_IMG VARCHAR(255) NOT NULL,
    AVAILABLE VARCHAR(10) DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS booking (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAR_ID INT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    BOOK_PLACE VARCHAR(255) NOT NULL,
    BOOK_DATE DATE NOT NULL,
    DURATION INT NOT NULL,
    PHONE_NUMBER BIGINT NOT NULL,
    DESTINATION VARCHAR(255) NOT NULL,
    PRICE INT NOT NULL,
    RETURN_DATE DATE NOT NULL,
    BOOK_STATUS VARCHAR(100) DEFAULT 'PENDING',
    FOREIGN KEY (CAR_ID) REFERENCES cars(CAR_ID) ON DELETE CASCADE,
    FOREIGN KEY (EMAIL) REFERENCES users(EMAIL) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payment (
    PAY_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID INT NOT NULL,
    CARD_NO VARCHAR(50) NOT NULL,
    EXP_DATE VARCHAR(10) NOT NULL,
    CVV INT NOT NULL,
    PRICE INT NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES booking(BOOK_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feedback (
    FED_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    COMMENT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS admin (
    ADMIN_ID VARCHAR(255) PRIMARY KEY,
    ADMIN_PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO admin (ADMIN_ID, ADMIN_PASSWORD) VALUES ('admin', 'admin')
ON DUPLICATE KEY UPDATE ADMIN_PASSWORD='admin';
